server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      #Генерация схемы БД на основе Entity
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  flyway:
    enabled: true
    locations:
      - db/migration

